
'use client';
import { useMemo, useState } from 'react';
export default function LeadFormModal({ open, onClose, lang='en' }) {
  const [submitting, setSubmitting] = useState(false);
  const tomorrow = useMemo(() => new Date(Date.now() + 86400000).toISOString().slice(0,10), []);
  if (!open) return null;
  return (<div className="overlay" role="dialog" aria-modal="true" onClick={(e)=>{ if(e.target===e.currentTarget) onClose(); }}><div className="modal"><div className="modal-head"><div><div className="eyebrow">Consultation request</div><h2>Request a private call</h2><p style={{color:'var(--muted)',margin:0}}>Share your property details, preferred time, and project scope.</p></div><button className="iconbtn" onClick={onClose} type="button">✕</button></div><iframe name="hidden_iframe" title="hidden_iframe" style={{display:'none'}} /><form action="https://script.google.com/macros/s/AKfycbwtoInpl_lZUmsvPkaMjQW_phwG-0Y4LCis8B11DSxIVRU7xf_6A9j24Yx1vlkSQTsx_A/exec" method="POST" target="hidden_iframe" onSubmit={()=>{setSubmitting(true); setTimeout(onClose,300);}} className="form-grid"><input type="hidden" name="lang" value={lang} /><div className="field"><label>Name</label><input name="name" required /></div><div className="field"><label>Email</label><input name="email" type="email" required /></div><div className="field"><label>Phone</label><input name="phone" type="tel" required /></div><div className="field"><label>Property location</label><input name="location" required /></div><div className="field"><label>Property type</label><select name="propertyType" required><option value="Villa">Villa</option><option value="Apartment">Apartment</option><option value="Historic property">Historic property</option><option value="Country house">Country house</option></select></div><div className="field"><label>Stage</label><select name="stage" required><option>Buying</option><option>Planning</option><option>Renovating</option><option>Maintaining</option></select></div><div className="field"><label>Estimated budget</label><input name="budget" /></div><div className="field"><label>Preferred call date</label><input name="callDate" type="date" min={tomorrow} required /></div><div className="field"><label>Preferred call time</label><input name="callTime" type="time" required /></div><div className="field full"><label>Project details</label><textarea name="message" rows="5" required /></div><div className="field full"><button className="btn primary" type="submit">{submitting ? 'Sending…' : 'Send request'}</button></div></form></div></div>);
}
