
'use client';
import { useState } from 'react';
import LeadFormModal from './LeadFormModal';
export default function SiteShell({ lang, messages, children }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [callOpen, setCallOpen] = useState(false);
  const navHref = (p) => `/${lang}${p}`;
  const switchLang = (e) => {
    const current = location.pathname.replace(/^\/(en|ru|it|zh)/, '') || '';
    location.pathname = `/${e.target.value}${current}`;
  };
  return (<div><header className="top"><div className="wrap bar"><a className="brand" href={navHref('')}>LuxuryItaly</a><nav className="nav"><a href={navHref('')}>{messages.navHome}</a><a href={navHref('/luxury-renovation-italy')}>{messages.service1}</a><a href={navHref('/property-restoration-italy')}>{messages.service2}</a><a href={navHref('/buy-and-renovate-property-italy')}>{messages.service3}</a><a href={navHref('/architecture-project-management-italy')}>{messages.service4}</a><a href={navHref('/property-maintenance-italy')}>{messages.service5}</a><a href={navHref('/portfolio')}>{messages.navPortfolio}</a><a href={navHref('/about')}>{messages.navAbout}</a><a href={navHref('/faq')}>{messages.navFaq}</a><a href={navHref('/contact')}>{messages.navContact}</a></nav><div className="actions"><select className="lang" defaultValue={lang} onChange={switchLang}><option value="en">EN</option><option value="ru">RU</option><option value="it">IT</option><option value="zh">中文</option></select><button className="btn menu" type="button" onClick={()=>setMenuOpen(true)}>{messages.menu}</button></div></div></header><div className="float"><button className="btn primary" onClick={()=>setCallOpen(true)}>{messages.requestCall}</button><a className="btn" href="https://wa.me/3900000000000">WhatsApp</a></div><div className={`overlay mobileOverlay ${menuOpen?'open':''}`} onClick={(e)=>{ if(e.target===e.currentTarget) setMenuOpen(false); }}><div className="mobilePanel"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><strong>LuxuryItaly</strong><button className="iconbtn" onClick={()=>setMenuOpen(false)} type="button">✕</button></div><nav><a href={navHref('')} onClick={()=>setMenuOpen(false)}>{messages.navHome}</a><a href={navHref('/luxury-renovation-italy')} onClick={()=>setMenuOpen(false)}>{messages.service1}</a><a href={navHref('/property-restoration-italy')} onClick={()=>setMenuOpen(false)}>{messages.service2}</a><a href={navHref('/buy-and-renovate-property-italy')} onClick={()=>setMenuOpen(false)}>{messages.service3}</a><a href={navHref('/architecture-project-management-italy')} onClick={()=>setMenuOpen(false)}>{messages.service4}</a><a href={navHref('/property-maintenance-italy')} onClick={()=>setMenuOpen(false)}>{messages.service5}</a><a href={navHref('/portfolio')} onClick={()=>setMenuOpen(false)}>{messages.navPortfolio}</a><a href={navHref('/about')} onClick={()=>setMenuOpen(false)}>{messages.navAbout}</a><a href={navHref('/faq')} onClick={()=>setMenuOpen(false)}>{messages.navFaq}</a><a href={navHref('/contact')} onClick={()=>setMenuOpen(false)}>{messages.navContact}</a></nav></div></div><LeadFormModal open={callOpen} onClose={()=>setCallOpen(false)} lang={lang} />{children}</div>);
}
